package ca.mcmaster.se2aa4.mazerunner;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

class PathGenerationTest {

  private Navigate maze1;
  private Navigate maze2;
  private Navigate maze3;

  @BeforeEach
  public void initializeMazes() {
    Logger logger = LogManager.getLogger();
    maze1 = new Navigate("./examples/test.maz.txt", logger, "");
    maze2 = new Navigate("./examples/rectangle.maz.txt", logger, "");
    maze3 = new Navigate("./examples/tiny_invalid.maz.txt", logger, "");
  }

  @Test
  void testSimplePathGeneration() {
    String expectedOutput = "FRFFLFFFFLFFRF\nF R 2F L 4F L 2F R F ";
    maze1.printAlgorithm();
    assertEquals(expectedOutput, maze1.getGeneratedPath());
  }

  @Test
  void testComplexPathGeneration() {
    String expectedOutput = "FRFFFFFFFLFFFFLLFFFFRFFRFFLLFFRFFFFFFFFFFFFFFFFRFFRFFFFFFFFFFFFFFLLFFFFRFFRFFFFFFLLFFFFRFFRFFFFFFLLFFRFFRFFLFFLLFFRFFLFFRFFFFRFFRFFLLFFRFFRFFFFLLFFFFRFFRFFFFFFLLFFFFFFRFFRFFFFFFLLFFFFRFFRFFFFLLFFRFFRFFLFFLLFFRFFLFFRFFLFFRFFRFFFFRFFLFFRFFLLFFRFFRFFLLFFLFFFFRFFLFFFFFFFFRFFLLFFRFFFFFFRFFRFFLLFFFFRFFFFFFRFFRFFFFLLFFRFFRFFLLFFRFFRFFFFLLFFFFLFFFFRFFRFFFFFFRFFFFLLFFFFRFFRFFFFFFLFFLLFFRFFRFFFFRFFLLFFRFFRFFLLFFRFFRFFFFLLFFFFRFFRFFFFLLFFFFRFFRFFFFFFFFFFRFFLLFFFFFFLLFFFFRFFFFFFFFRFFRFFFFFFLLFFFFRFFRFFFFLLFFRFFRFFFFLFFFFFFLLFFFFFFRFFRFFFFLLFFFFRFFRFFFFLLFFFFFFRFFRFFFFLLFFFFFFRFFRFFLLFFFFRFFRFFLFFRFFRFFLFFRFFLLFFLFFRFFLFFLFFRFFRFFLLFFRFFFFFFRFFFFRFFRFFLFFLLFFRFFLFFLFFRFFLLFFRFFRFFFFFFRFFFFRFFRFFLLFFLFFFFRFFRFFFFLFFRFFRFFFFLLFFRFFFFLLFFFFRFFRFFFFFFRFFFFLLFFFFRFFRFFFFLFFFFFFRFFLFFRFFFFLLFFFFRFFRFFFFFFLLFFRFFRFFFFFFLLFFRFFRFFFFLLFFRFFRFFLLFFLFFRFFLFFRFFFFRFFRFFLLFFRFFRFFFFLLFFFFRFFRFFFFFFLLFFFFFFRFFRFFFFFFFFRFFLLFFLFFFFFFRFFRFFFFFFLFFLLFFRFFRFFLLFFRFFRFFLLFFRFFLFFRFFRFFLLFFRFFRFFFFRFFFFLLFFFRF\nF R 7F L 4F 2L 4F R 2F R 2F 2L 2F R 16F R 2F R 14F 2L 4F R 2F R 6F 2L 4F R 2F R 6F 2L 2F R 2F R 2F L 2F 2L 2F R 2F L 2F R 4F R 2F R 2F 2L 2F R 2F R 4F 2L 4F R 2F R 6F 2L 6F R 2F R 6F 2L 4F R 2F R 4F 2L 2F R 2F R 2F L 2F 2L 2F R 2F L 2F R 2F L 2F R 2F R 4F R 2F L 2F R 2F 2L 2F R 2F R 2F 2L 2F L 4F R 2F L 8F R 2F 2L 2F R 6F R 2F R 2F 2L 4F R 6F R 2F R 4F 2L 2F R 2F R 2F 2L 2F R 2F R 4F 2L 4F L 4F R 2F R 6F R 4F 2L 4F R 2F R 6F L 2F 2L 2F R 2F R 4F R 2F 2L 2F R 2F R 2F 2L 2F R 2F R 4F 2L 4F R 2F R 4F 2L 4F R 2F R 10F R 2F 2L 6F 2L 4F R 8F R 2F R 6F 2L 4F R 2F R 4F 2L 2F R 2F R 4F L 6F 2L 6F R 2F R 4F 2L 4F R 2F R 4F 2L 6F R 2F R 4F 2L 6F R 2F R 2F 2L 4F R 2F R 2F L 2F R 2F R 2F L 2F R 2F 2L 2F L 2F R 2F L 2F L 2F R 2F R 2F 2L 2F R 6F R 4F R 2F R 2F L 2F 2L 2F R 2F L 2F L 2F R 2F 2L 2F R 2F R 6F R 4F R 2F R 2F 2L 2F L 4F R 2F R 4F L 2F R 2F R 4F 2L 2F R 4F 2L 4F R 2F R 6F R 4F 2L 4F R 2F R 4F L 6F R 2F L 2F R 4F 2L 4F R 2F R 6F 2L 2F R 2F R 6F 2L 2F R 2F R 4F 2L 2F R 2F R 2F 2L 2F L 2F R 2F L 2F R 4F R 2F R 2F 2L 2F R 2F R 4F 2L 4F R 2F R 6F 2L 6F R 2F R 8F R 2F 2L 2F L 6F R 2F R 6F L 2F 2L 2F R 2F R 2F 2L 2F R 2F R 2F 2L 2F R 2F L 2F R 2F R 2F 2L 2F R 2F R 4F R 4F 2L 3F R F ";
    maze2.printAlgorithm();
    assertEquals(expectedOutput, maze2.getGeneratedPath());
  }

  @Test
  void testInvalidPathGeneration() {
    String expectedOutput = "";
    maze3.printAlgorithm();
    assertEquals(expectedOutput, maze3.getGeneratedPath());
  }
}
